# Dependabot configuration for V2Ray Monitor Module

version: 2
updates:
  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Gugun09"
    assignees:
      - "Gugun09"
    commit-message:
      prefix: "🔄"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"

  # Monitor any npm dependencies (if added in the future)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "Gugun09"
    assignees:
      - "Gugun09"
    commit-message:
      prefix: "📦"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
    # Ignore major version updates for stability
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]