name: ✨ Feature Request
description: Suggest a new feature or enhancement for V2Ray Monitor Module
title: "[FEATURE] "
labels: ["enhancement", "needs-review"]
assignees: ["Gugun09"]

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request
        
        Thank you for suggesting a new feature! Please fill out the form below to help us understand your request.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please check the following before submitting
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have checked the roadmap to see if this feature is already planned
          required: true
        - label: This feature would benefit other users, not just myself
          required: true

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - UI/UX Enhancement
        - New Monitoring Feature
        - Integration (Telegram, etc.)
        - Performance Improvement
        - Security Enhancement
        - Configuration Option
        - API Enhancement
        - Other
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature in detail
    validations:
      required: true

  - type: textarea
    id: problem_statement
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current limitation?
      placeholder: Explain the problem or limitation this feature would address
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe any alternative approaches you've considered

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Provide specific examples of how this feature would be used
      placeholder: |
        Example scenarios:
        1. When user wants to...
        2. In the case where...
        3. For users who need to...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important for my use case
        - Critical for my workflow
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (UI changes, config options)
        - Medium (new functionality, integrations)
        - Complex (major changes, new systems)
        - I'm not sure

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Examples
      description: If applicable, provide mockups, screenshots, or examples from other applications

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any other context, links, or references about the feature request

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing to this feature?
      options:
        - label: I would be willing to help test this feature
        - label: I would be willing to help with documentation
        - label: I would be willing to contribute code (if I have the skills)
        - label: I can provide ongoing feedback during development